#!/usr/bin/env python3
"""Phase 8 groom generator: a dense fur coat over a spherical critter.

Writes tests/fixtures/groom_archive.rib — one huge Curves request (cubic
b-spline strands with clumping, droop, and noise) — which furball.rib
pulls in via ReadArchive.

Usage: python3 scripts/gen_groom.py [strands]  (default 250000)
"""

import math
import random
import sys
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "tests" / "fixtures" / "groom_archive.rib"

random.seed(20260829)


def hash01(i, j):
    h = (i * 374761393 + j * 668265263) & 0xFFFFFFFF
    h = (h ^ (h >> 13)) * 1274126177 & 0xFFFFFFFF
    return ((h ^ (h >> 16)) & 0xFFFF) / 65535.0


def main():
    n_strands = int(sys.argv[1]) if len(sys.argv) > 1 else 250_000
    ctrl_per = 5

    # Clump centers: strands bend toward the nearest of ~600 tufts.
    clumps = []
    for _ in range(600):
        z = random.uniform(-1, 1)
        phi = random.uniform(0, 2 * math.pi)
        r = math.sqrt(max(0.0, 1 - z * z))
        clumps.append((r * math.cos(phi), z, r * math.sin(phi)))

    nv = []
    pieces = []
    for i in range(n_strands):
        # Fibonacci-ish sphere scatter with jitter (full coverage).
        z = 1.0 - 2.0 * ((i + 0.5) / n_strands)
        phi = i * 2.399963229728653 + random.uniform(-0.02, 0.02)
        z = max(-0.999, min(0.999, z + random.uniform(-0.004, 0.004)))
        r = math.sqrt(max(0.0, 1 - z * z))
        nx, ny, nz = r * math.cos(phi), z, r * math.sin(phi)

        # Nearest clump direction (cheap: sample a few).
        best, bd = None, 1e9
        for k in range(6):
            c = clumps[(i * 7 + k * 97) % len(clumps)]
            d = (c[0] - nx) ** 2 + (c[1] - ny) ** 2 + (c[2] - nz) ** 2
            if d < bd:
                bd, best = d, c
        cx, cy, cz = best

        ln = 0.28 + 0.20 * hash01(i, 3) + 0.06 * math.sin(nx * 9) * math.cos(nz * 7)
        # Face mask: trim the coat where the muzzle lives (local -z,
        # slightly below the equator) so eyes and nose read.
        face = -(nz * 0.97 + ny * -0.24)
        if face > 0.72:
            t_mask = min(1.0, (face - 0.72) / 0.2)
            ln *= 1.0 - 0.8 * t_mask
        # Guard hairs: 3% extra-long wispy strands.
        guard = hash01(i, 11) > 0.97
        if guard:
            ln *= 1.8

        droop = 0.5 * ln
        clump_pull = 0.35
        jx = 0.10 * ln * (hash01(i, 5) - 0.5)
        jz = 0.10 * ln * (hash01(i, 6) - 0.5)
        for k in range(ctrl_per):
            t = k / (ctrl_per - 1)
            g = 1.0 + ln * t
            # Blend the root normal toward the clump center as t grows.
            bx = nx + (cx - nx) * clump_pull * t * t
            by = ny + (cy - ny) * clump_pull * t * t
            bz = nz + (cz - nz) * clump_pull * t * t
            bl = math.sqrt(bx * bx + by * by + bz * bz)
            bx, by, bz = bx / bl, by / bl, bz / bl
            px = bx * g + jx * t * t
            py = by * g - droop * t * t
            pz = bz * g + jz * t * t
            pieces.append(f"{px:.4f} {py:.4f} {pz:.4f}")
        nv.append(ctrl_per)

    with open(OUT, "w") as f:
        f.write("# generated by scripts/gen_groom.py — %d strands\n" % n_strands)
        f.write('Basis "b-spline" 1 "b-spline" 1\n')
        f.write('Curves "cubic" [')
        f.write(" ".join(str(v) for v in nv))
        f.write('] "nonperiodic"\n"P" [')
        f.write(" ".join(pieces))
        f.write(']\n"width" [0.0045 0.0012]\n')
    print(f"wrote {OUT} ({n_strands} strands, {OUT.stat().st_size / 1e6:.1f} MB)")


if __name__ == "__main__":
    main()
