#!/usr/bin/env python3
"""Phase 9 stress scene: a firefly forest at dusk.

Writes tests/fixtures/forest_*.rib pieces pulled together by forest.rib:
  forest_defs.rib      3 tree archetypes + a rock (ObjectBegin meshes)
  forest_instances.rib tree/rock placements (ObjectInstance per item);
                       binary-encode with `render catrib --binary` after
  forest_grass.rib     linear-curve grass fields near the camera
  forest_lights.rib    1200+ firefly point lights + visible glow spheres

Usage: python3 scripts/gen_forest.py [tree_instances] (default 400000)
"""

import math
import random
import sys
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "tests" / "fixtures"
random.seed(20260830)

# Camera looks down +z; the clearing runs z in [6, 120], x in [-60, 60].


def tapered_tube(sides, r0, r1, y0, y1, twist=0.0):
    """Vertices+quads for one trunk/canopy segment ring pair."""
    verts, quads = [], []
    for k in range(sides):
        a = 2 * math.pi * k / sides + twist
        verts.append((r0 * math.cos(a), y0, r0 * math.sin(a)))
    for k in range(sides):
        a = 2 * math.pi * k / sides + twist
        verts.append((r1 * math.cos(a), y1, r1 * math.sin(a)))
    for k in range(sides):
        k2 = (k + 1) % sides
        quads.append((k, k2, sides + k2, sides + k))
    return verts, quads


def mesh_rib(verts, polys):
    nv = " ".join(str(len(p)) for p in polys)
    idx = " ".join(" ".join(str(i) for i in p) for p in polys)
    pts = " ".join(f"{x:.3f} {y:.3f} {z:.3f}" for x, y, z in verts)
    return f'PointsPolygons [{nv}] [{idx}]\n  "P" [{pts}]\n'


def tree(kind):
    """One tree archetype as (trunk_rib, canopy_rib)."""
    verts, polys = [], []

    def add(vs, qs):
        base = len(verts)
        verts.extend(vs)
        polys.extend(tuple(base + i for i in q) for q in qs)

    h = 5.0 + kind * 1.5
    # Trunk: 3 stacked tapered tubes.
    radii = [0.28, 0.2, 0.13, 0.05]
    ys = [0.0, h * 0.35, h * 0.7, h]
    for s in range(3):
        add(*tapered_tube(7, radii[s], radii[s + 1], ys[s], ys[s + 1], s * 0.3))
    trunk = mesh_rib(verts, polys)

    verts, polys = [], []
    # Canopy: stacked cones (conifer) or blobs (deciduous-ish).
    if kind < 2:
        tiers = 3 + kind
        for t in range(tiers):
            y = h * (0.35 + 0.55 * t / tiers)
            r = (1.9 - 0.42 * t) * (1.0 + 0.12 * kind)
            top = y + h * 0.28
            vs, qs = tapered_tube(8, r, 0.03, y, top, t * 0.4)
            add(vs, qs)
    else:
        # Blob: two wide tubes forming a rough ellipsoid.
        add(*tapered_tube(8, 1.0, 2.3, h * 0.5, h * 0.75))
        add(*tapered_tube(8, 2.3, 0.8, h * 0.75, h * 1.1, 0.35))
    canopy = mesh_rib(verts, polys)
    return trunk, canopy


def rock():
    verts, polys = [], []
    vs, qs = tapered_tube(7, 0.7, 1.0, 0.0, 0.4, 0.2)
    verts.extend(vs)
    polys.extend(qs)
    vs2, qs2 = tapered_tube(7, 1.0, 0.35, 0.4, 0.9, 0.5)
    base = len(verts)
    verts.extend(vs2)
    polys.extend(tuple(base + i for i in q) for q in qs2)
    return mesh_rib(verts, polys)


def write_defs():
    greens = ["0.05 0.16 0.05", "0.08 0.2 0.06", "0.13 0.17 0.05"]
    with open(OUT / "forest_defs.rib", "w") as f:
        f.write("# generated by scripts/gen_forest.py\n")
        for k in range(3):
            trunk, canopy = tree(k)
            f.write(f'ObjectBegin "tree{k}"\n')
            f.write('Bxdf "PxrSurface" "bark" "diffuseColor" [0.16 0.11 0.07] '
                    '"diffuseRoughness" [0.6] "specularIor" [1]\n')
            f.write(trunk)
            f.write(f'Bxdf "PxrSurface" "leaves" "diffuseColor" [{greens[k]}] '
                    '"diffuseRoughness" [0.5] "specularIor" [1.2] '
                    '"specularRoughness" [0.5]\n')
            f.write(canopy)
            f.write("ObjectEnd\n")
        f.write('ObjectBegin "rock"\n')
        f.write('Bxdf "PxrSurface" "stone" "diffuseColor" [0.22 0.21 0.2] '
                '"specularIor" [1.3] "specularRoughness" [0.45]\n')
        f.write(rock())
        f.write("ObjectEnd\n")


def ground_height(x, z):
    return (math.sin(x * 0.045) * math.cos(z * 0.05) * 1.8
            + math.sin(x * 0.013 + 2.0) * 2.5)


def write_instances(n):
    lines = []
    placed = 0
    attempts = 0
    while placed < n and attempts < n * 3:
        attempts += 1
        x = random.uniform(-220, 220)
        z = random.uniform(4, 460)
        # A clear wedge down the middle: wide at the camera, narrowing
        # into the distance, so the eye travels into the woods.
        if z < 150:
            half = 7.0 + (150.0 - z) * 0.10
            if abs(x) < half:
                continue
        y = ground_height(x, z)
        kind = random.randrange(3)
        s = random.uniform(0.55, 1.5)
        rot = random.uniform(0, 360)
        obj = f"tree{kind}" if random.random() > 0.07 else "rock"
        lines.append(
            f"TransformBegin\nTranslate {x:.2f} {y:.2f} {z:.2f}\n"
            f"Rotate {rot:.1f} 0 1 0\nScale {s:.3f} {s:.3f} {s:.3f}\n"
            f'ObjectInstance "{obj}"\nTransformEnd'
        )
        placed += 1
    # Hero trees inside the clearing for depth.
    for hx, hz, hs in [(-4.5, 52, 1.1), (5.0, 84, 1.3), (-3.5, 118, 0.9), (6.5, 132, 1.2)]:
        hy = ground_height(hx, hz)
        lines.append(
            f"TransformBegin\nTranslate {hx:.2f} {hy:.2f} {hz:.2f}\n"
            f"Rotate {random.uniform(0, 360):.1f} 0 1 0\nScale {hs} {hs} {hs}\n"
            f'ObjectInstance "tree{random.randrange(3)}"\nTransformEnd'
        )
        placed += 1
    with open(OUT / "forest_instances.rib", "w") as f:
        f.write("\n".join(lines))
        f.write("\n")
    return placed


def write_grass(strands):
    with open(OUT / "forest_grass.rib", "w") as f:
        f.write('Bxdf "PxrMarschnerHair" "grass" "color" [0.1 0.3 0.05] '
                '"roughness" [0.5] "azimuthalRoughness" [0.5]\n')
        nv, pts = [], []
        for i in range(strands):
            # Concentrate near the camera path.
            z = 6 + 130 * random.random() ** 1.6
            half = 7.0 + max(0.0, 150.0 - z) * 0.10
            x = random.uniform(-half - 4, half + 4)
            y = ground_height(x, z)
            h = random.uniform(0.25, 0.7)
            bx = random.uniform(-0.25, 0.25) * h
            bz = random.uniform(-0.25, 0.25) * h
            nv.append(4)
            for k in range(4):
                t = k / 3.0
                pts.append(f"{x + bx * t * t:.3f} {y + h * t:.3f} {z + bz * t * t:.3f}")
        f.write(f'Curves "linear" [{" ".join(str(v) for v in nv)}] "nonperiodic"\n')
        f.write(f'"P" [{" ".join(pts)}]\n"width" [0.02 0.004]\n')


def write_lights(n_fireflies, n_glows):
    with open(OUT / "forest_lights.rib", "w") as f:
        f.write("# fireflies: the many-light stress (light BVH)\n")
        for i in range(n_fireflies):
            # Two thirds hover in the visible wedge, the rest deep.
            if random.random() < 0.65:
                z = 8 + 140 * random.random() ** 1.4
                half = 7.0 + max(0.0, 150.0 - z) * 0.10
                x = random.uniform(-half - 6, half + 6)
            else:
                z = random.uniform(60, 380)
                x = random.uniform(-140, 140)
            y = ground_height(x, z) + random.uniform(0.3, 2.4)
            warm = random.random() < 0.8
            c = "1.0 0.72 0.25" if warm else "0.5 0.8 1.0"
            inten = random.uniform(1.2, 4.0)
            f.write(f'LightSource "pointlight" "fly{i}" "from" [{x:.2f} {y:.2f} {z:.2f}] '
                    f'"intensity" [{inten:.2f}] "lightcolor" [{c}]\n')
        f.write('\nBxdf "PxrSurface" "glow" "diffuseGain" [0] '
                '"glowGain" [14] "glowColor" [1.0 0.72 0.25]\n')
        for _ in range(n_glows):
            z = random.uniform(8, 90)
            half = 7.0 + max(0.0, 150.0 - z) * 0.10
            x = random.uniform(-half - 3, half + 3)
            y = ground_height(x, z) + random.uniform(0.4, 2.2)
            f.write(f"TransformBegin Translate {x:.2f} {y:.2f} {z:.2f} "
                    "Sphere 0.05 -0.05 0.05 360 TransformEnd\n")


def write_ground():
    # Grid matching ground_height so instances sit exactly on the floor.
    nx, nz = 120, 160
    x0, x1, z0, z1 = -240.0, 240.0, 0.0, 480.0
    verts, quads = [], []
    for j in range(nz + 1):
        for i in range(nx + 1):
            x = x0 + (x1 - x0) * i / nx
            z = z0 + (z1 - z0) * j / nz
            verts.append((x, ground_height(x, z), z))
    for j in range(nz):
        for i in range(nx):
            a = j * (nx + 1) + i
            quads.append((a, a + 1, a + nx + 2, a + nx + 1))
    with open(OUT / "forest_ground.rib", "w") as f:
        f.write(mesh_rib(verts, quads))


def main():
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 400_000
    write_defs()
    write_ground()
    placed = write_instances(n)
    write_grass(220_000)
    write_lights(1200, 60)
    print(f"defs + {placed} instances + grass + lights written to {OUT}")
    print("now: ./target/release/render catrib --binary "
          "tests/fixtures/forest_instances.rib tests/fixtures/forest_instances.brib")


if __name__ == "__main__":
    main()
