#!/usr/bin/env python3
"""Generate the Phase-2 'instanced glade' stress scene: a high-poly
trefoil-knot mesh archive (PointsPolygons) instanced thousands of times
via ObjectInstance.

Usage: gen_glade.py OUTDIR [--tris 1000000] [--instances 10000]
Writes OUTDIR/knot.rib (mesh archive) and OUTDIR/glade.rib (scene).
"""

import argparse
import math
import random


def knot_mesh(target_tris):
    """Trefoil knot tube as (positions, normals, quads)."""
    # quads = along * around; tris = 2 * quads
    around = max(8, int(math.sqrt(target_tris / 2 / 8)))
    along = max(16, target_tris // (2 * around))

    positions = []
    normals = []
    tube_r = 0.35

    for i in range(along):
        t = 2.0 * math.pi * i / along
        # Trefoil curve and its tangent.
        c3, s3 = math.cos(3 * t), math.sin(3 * t)
        c2, s2 = math.cos(2 * t), math.sin(2 * t)
        px = (2 + c3) * c2
        py = (2 + c3) * s2
        pz = s3
        dx = -3 * s3 * c2 - 2 * (2 + c3) * s2
        dy = -3 * s3 * s2 + 2 * (2 + c3) * c2
        dz = 3 * c3
        tl = math.sqrt(dx * dx + dy * dy + dz * dz)
        tx, ty, tz = dx / tl, dy / tl, dz / tl
        # Frame: pick a stable normal via projection of z-axis.
        nx, ny, nz = -tz * tx, -tz * ty, 1 - tz * tz
        nl = math.sqrt(nx * nx + ny * ny + nz * nz) or 1.0
        nx, ny, nz = nx / nl, ny / nl, nz / nl
        bx = ty * nz - tz * ny
        by = tz * nx - tx * nz
        bz = tx * ny - ty * nx

        for j in range(around):
            a = 2.0 * math.pi * j / around
            ca, sa = math.cos(a), math.sin(a)
            ox = ca * nx + sa * bx
            oy = ca * ny + sa * by
            oz = ca * nz + sa * bz
            positions.append((px + tube_r * ox, py + tube_r * oy, pz + tube_r * oz))
            normals.append((ox, oy, oz))

    quads = []
    for i in range(along):
        for j in range(around):
            a = i * around + j
            b = i * around + (j + 1) % around
            c = ((i + 1) % along) * around + (j + 1) % around
            d = ((i + 1) % along) * around + j
            quads.append((a, b, c, d))
    return positions, normals, quads


def write_archive(path, positions, normals, quads):
    with open(path, "w") as f:
        f.write("# generated by gen_glade.py\n")
        f.write("PointsPolygons [")
        f.write(" ".join("4" for _ in quads))
        f.write("]\n[")
        f.write(" ".join(f"{a} {b} {c} {d}" for a, b, c, d in quads))
        f.write("]\n\"P\" [")
        f.write(" ".join(f"{x:.5f} {y:.5f} {z:.5f}" for x, y, z in positions))
        f.write("]\n\"N\" [")
        f.write(" ".join(f"{x:.5f} {y:.5f} {z:.5f}" for x, y, z in normals))
        f.write("]\n")


def write_scene(path, archive_name, instances):
    rng = random.Random(20260829)
    grid = int(math.sqrt(instances))
    lines = [
        "##RenderMan RIB-Structure 1.1",
        "version 3.04",
        'Display "glade.exr" "file" "rgb"',
        "Format 1280 720 1.0",
        'Projection "perspective" "fov" [42]',
        'Option "background" "color" [0.78 0.87 1.0]',
        "# Camera: 7 units up, pitched down 10 degrees (world-to-camera CTM)",
        "Rotate -8 1 0 0",
        "Translate 0 -7 0",
        "WorldBegin",
        '    LightSource "distantlight" "sun" "from" [30 40 -20] "to" [0 0 60] "intensity" [1.6]',
        "    # Sky: one big soft overhead panel",
        "    AttributeBegin",
        '        AreaLightSource "arealight" "sky" "intensity" [1.1] "lightcolor" [0.75 0.85 1.0]',
        '        Polygon "P" [-12000 110 -12000  12000 110 -12000  12000 110 12000  -12000 110 12000]',
        "    AttributeEnd",
        "    # Ground",
        "    AttributeBegin",
        "        Color 0.32 0.36 0.26",
        '        Surface "matte"',
        '        Polygon "P" [-12000 -1.2 -100  12000 -1.2 -100  12000 -1.2 12000  -12000 -1.2 12000]',
        "    AttributeEnd",
        "    # Knot masters",
    ]
    palettes = [
        ("copper", "metal", "0.88 0.55 0.35", "0.12"),
        ("jade", "plastic", "0.28 0.62 0.45", "0.2"),
        ("bone", "matte", "0.78 0.74 0.66", "0.3"),
    ]
    for name, surface, color, rough in palettes:
        lines += [
            f'    ObjectBegin "{name}"',
            f"        Color {color}",
            f'        Surface "{surface}" "roughness" [{rough}]',
            f'        ReadArchive "{archive_name}"',
            "    ObjectEnd",
        ]
    lines.append("    # The glade")
    count = 0
    for gy in range(grid):
        for gx in range(grid):
            if count >= instances:
                break
            x = (gx - grid / 2) * 4.2 + rng.uniform(-1.2, 1.2)
            z = 14 + gy * 4.2 + rng.uniform(-1.2, 1.2)
            s = rng.uniform(0.28, 0.5)
            rot = rng.uniform(0, 360)
            tilt = rng.uniform(-25, 25)
            which = rng.choice(palettes)[0]
            lines += [
                "    TransformBegin",
                f"        Translate {x:.2f} {s * 2.4 - 1.2:.2f} {z:.2f}",
                f"        Rotate {rot:.1f} 0 1 0",
                f"        Rotate {tilt:.1f} 1 0 0",
                f"        Scale {s:.3f} {s:.3f} {s:.3f}",
                f'        ObjectInstance "{which}"',
                "    TransformEnd",
            ]
            count += 1
    lines.append("WorldEnd")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("outdir")
    ap.add_argument("--tris", type=int, default=1_000_000)
    ap.add_argument("--instances", type=int, default=10_000)
    args = ap.parse_args()

    positions, normals, quads = knot_mesh(args.tris)
    print(f"knot: {len(positions)} verts, {2 * len(quads)} tris")
    write_archive(f"{args.outdir}/knot.rib", positions, normals, quads)
    write_scene(f"{args.outdir}/glade.rib", "knot.rib", args.instances)
    print(f"wrote {args.outdir}/knot.rib and {args.outdir}/glade.rib")


if __name__ == "__main__":
    main()
